# Generated by Django 5.0.6 on 2024-05-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=1000)),
                ('firm_name', models.CharField(max_length=1000)),
                ('gst', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
