# Generated by Django 5.0.6 on 2024-05-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerenquiry',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
